resolver: lts-21.24

ghc-options:
  # locally install Haddocs for "everything": deps and the project
  $everything: -haddock
  # speed up project build via module-parallel compile in GHC itself
  $targets: -j

packages:
  - examples/warp-wamp-router
  - wamp
  - wamp-client
  - wamp-common
  - wamp-router

extra-deps:
  - ixset-1.1.1.2
  - syb-with-class-0.6.1.14

flags:
  cryptonite:
    support_aesni: true
  mintty:
    Win32-2-13-1: false
