flags: {}
packages:
- examples/warp-wamp-router
- wamp
- wamp-client
- wamp-common
- wamp-router
extra-deps:
- wuss-1.1.18
- ixset-1.1.1.1
- syb-with-class-0.6.1.13
resolver: lts-18.19
allow-newer: true
flags:
  cryptonite:
    support_aesni: true
  mintty:
    Win32-2-13-1: false
