flags: {}
packages:
- examples/warp-wamp-router
- wamp
- wamp-client
- wamp-common
- wamp-router
extra-deps:
- wuss-1.1.18
resolver: lts-20.13
allow-newer: true
flags:
  cryptonite:
    support_aesni: true
  mintty:
    Win32-2-13-1: false
