name:         wamp-client
version:      "0.1.0.0"
author:       Maciej Kazulak
maintainer:   kazulakm@gmail.com
stability:    experimental
license:      MIT 
license-file: LICENSE
category:     Network
build-type:   Simple

default-extensions:
  - OverloadedStrings

extra-source-files:
  - README.md


library:
  exposed-modules:
    - Network.Wamp.Client
  other-modules:
    - Network.Wamp.Auth
    - Network.Wamp.State
    - Network.Wamp.Cryptosign
  dependencies:
    - aeson
    - async
    - base
    - base16-bytestring
    - bytestring
    - ed25519
    - ixset
    - random
    - text
    - unordered-containers
    - vector
    - wamp-common
    - websockets
    - wuss
    