name:         wamp-common
version:      0.1.2.0
description:  Web Application Messaging Protocol v2 Basic Profile
              building blocks common to both Client and Router.
author:       Maciej Kazulak
maintainer:   kazulakm@gmail.com
stability:    experimental
license:      MIT 
license-file: LICENSE
category:     Network
build-type:   Simple

# GHC's GHC2021 language extension is supported by GHC >= 9.2.1
# for more details see: https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0380-ghc2021.rst
language: GHC2021

default-extensions:
  - OverloadedStrings

library:
  exposed-modules:
    - Network.Wamp.Connection
    - Network.Wamp.Messages
    - Network.Wamp.Types
  dependencies:
    - aeson
    - base
    - bytestring
    - hashable
    - text
    - unordered-containers
    - vector
    - websockets
