name:         wamp-router
version:      0.1.2.0
author:       Maciej Kazulak
maintainer:   kazulakm@gmail.com
stability:    experimental
license:      MIT 
license-file: LICENSE
category:     Network
build-type:   Simple

# GHC's GHC2021 language extension is supported by GHC >= 9.2.1
# for more details see: https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0380-ghc2021.rst
language: GHC2021

default-extensions:
  - DataKinds
  - OverloadedStrings

library:
  exposed-modules:
    - Network.Wamp.Router
    - Network.Wamp.Broker
    - Network.Wamp.Dealer
  dependencies:
    - aeson
    - base
    - bytestring
    - ixset-typed 
    - random
    - unordered-containers
    - wamp-common
    - websockets
